service: sls-swapi-v1
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:sa-east-1:862454797065:table/CharactersTable

functions:
  getPeople:
    handler: dist/routes/people.getPeople
    events:
      - httpApi:
          path: /personas
          method: get
  createPerson:
    handler: dist/routes/people.addPerson
    events:
      - httpApi:
          path: /personas
          method: post
  app:
    handler: dist/swagger.handler
    events:
      - httpApi:
          path: /api-docs
          method: get
  login:
    handler: dist/routes/login.login
    events:
      - httpApi:
          path: /login
          method: post
  validateToken:
    handler: dist/routes/validate.validateToken
    events:
      - httpApi:
          path: /validate-token
          method: get
resources:
  Resources:
    CharactersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CharactersTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  - serverless-offline
